### ISSUE TITLE
Export as RTF is incomplete

### ISSUE THREAD

**Issue by yshorish** [CDLUC3/dmptool#40] opened 2014-07-03 12:52 UTC
Exporting to RTF only captures part of the DMP. Attached screen cap cuts off in the middle of Section 3 even though plan previews all 5 sections. 
![rtf-error](https://cloud.githubusercontent.com/assets/7841314/3469594/e7281a4c-02b0-11e4-8464-22a005f54fa4.png)

**Comment by mxsstrong** [comment] 2015-11-10 05:03
we now offer the ability to download in DOCX.  We need to ensure this issue isn't happening with DOCX.  If not, close the issue

**Comment by stephaniesimms** [comment] 2015-11-20 23:36
tested exporting longer test plans in DOCX and could not reproduce this problem

**Closed by stephaniesimms** 2015-11-20 23:36 UTC
Labels: bug, medium priority, more info needed
